apiVersion: v1
kind: Service
metadata:
  name: react-app
  labels:
    app: netflix-app
spec:
  ports:
    - name: nodejs
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: "{{ .Values.service.type }}"
  selector:
    app: netflix-app
    tier: web
